services:
  reporting-db:
    image: postgres:16-alpine
    container_name: reporting-db
    environment:
      POSTGRES_DB: reporting
      POSTGRES_USER: reporting_user
      POSTGRES_PASSWORD: reporting_pass
    ports:
      - "5433:5432"
    volumes:
      - reporting_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reporting_user -d reporting"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  metabase:
    image: metabase/metabase:v0.56.9
    container_name: metabase
    depends_on:
      reporting-db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data
    restart: unless-stopped
    
volumes:
  reporting_pgdata:
  metabase_data: